import {describe,it,expect} from 'vitest';
import {estimateMadridIncomeTax,incomeScale,stateIncomeBands2026,madridIncomeBands2026,employmentReduction2026,employmentDeduction2026} from './income-tax';
import {annualTax,yearCalculation} from './engine';
import {defaultState,blankMonth,buildGradeDates} from './model';
import {applyWorkProfile,builtinWorkProfiles} from './work-profiles';

// Synthetic inputs. Fixed expected amounts calculated independently with Decimal
// from the printed legal scales; never generated by the implementation under test.
describe('Renta Madrid 2026 separada de retenciones',()=>{
 it.each([
  [0,0,0,0,0,0,0,0],
  [30000,2000,26000,2455.50,2128.62,0,4584.12,415.88],
  [40000,2600,35400,3872.50,3331.82,0,7204.32,-2204.32],
  [17094,1100,8690.50,298.35,232.37,530.72,0,5000],
  [18000,1200,10907,508.92,420.78,409.69,520.01,4479.99],
 ])('bruto %s, SS %s: cuotas, deducción y saldo', (gross,ss,base,stateQuota,madridQuota,employmentDeduction,liability,refund)=>{
  const withheld=gross?5000:0;
  expect(estimateMadridIncomeTax(2026,gross,ss,withheld)).toMatchObject({available:true,base,stateQuota,madridQuota,employmentDeduction,liability,balance:-refund||0});
 });

 it('transcribe los umbrales y cuotas publicadas, incluidos tipos superiores',()=>{
  const state=[[0,0],[12450,1182.75],[20200,2112.75],[35200,4362.75],[60000,8950.75],[300000,62950.75],[310000,65400.75]];
  const madrid=[[0,0],[13362.22,1135.79],[19004.63,1739.53],[35425.68,3841.42],[57320.40,7651.10],[67320.40,9701.10]];
  for(const [base,quota] of state)expect(incomeScale(base,stateIncomeBands2026)).toBe(quota);
  for(const [base,quota] of madrid)expect(incomeScale(base,madridIncomeBands2026)).toBe(quota);
  for(const bands of [stateIncomeBands2026,madridIncomeBands2026])for(const band of bands.slice(1)){
   const below=incomeScale(band.from-.01,bands),at=incomeScale(band.from,bands),above=incomeScale(band.from+.01,bands);
   expect(Math.abs(at-below)).toBeLessThan(.011);expect(Math.abs(above-at)).toBeLessThan(.011);
  }
 });

 it('reducción y deducción respetan límites sin descontar dos veces los 2000 euros',()=>{
  for(const [net,amount] of [[14852,7302],[14852.01,7301.98],[17673.52,2364.34],[17673.53,2364.33],[19747.49,0.01],[19747.5,0]])expect(employmentReduction2026(net)).toBe(amount);
  for(const [gross,amount] of [[17094,590.89],[17094.05,590.88],[18000,409.69],[20048.4,.01],[20048.45,0]])expect(employmentDeduction2026(gross)).toBe(amount);
  expect(estimateMadridIncomeTax(2026,1000,100,150)).toMatchObject({generalExpenses:900,reduction:0,base:0,liability:0,balance:-150});
 });

 it('no usa el mínimo MIR, el límite del 43 % ni la escala conjunta de retenciones en Renta',()=>{
  const s=applyWorkProfile(defaultState(),builtinWorkProfiles[0]).settings;
  expect(annualTax(18000,1200,s)).toMatchObject({percent:15,annualWithheld:2700});
  expect(estimateMadridIncomeTax(2026,18000,1200,2700)).toMatchObject({liability:520.01,balance:-2179.99});
  // AEAT example: 24,000 base gives 5,365.50 before personal-minimum tax.
  expect(annualTax(28000,2000,s)).toMatchObject({base:24000,quota:4311,percent:15.39});
 });

 it('no ofrece cifras para años sin verificar o entradas incoherentes',()=>{
  for(const year of [2025,2027,2031])expect(estimateMadridIncomeTax(year,30000,2000,5000)).toMatchObject({available:false,year});
  for(const [gross,ss,withheld] of [[100,101,0],[-1,0,0],[100,0,-1],[NaN,0,0],[100,Infinity,0]])expect(estimateMadridIncomeTax(2026,gross,ss,withheld).available).toBe(false);
 });

 it('integra acumulados y recibos sin duplicar, y respeta los ajustes anuales solo en su ejercicio',()=>{
  const state=applyWorkProfile(defaultState(),builtinWorkProfiles[0]);
  Object.assign(state.settings,{profileComplete:true,residencyStart:'2025-06-01',residencyEnd:'2029-05-31',gradeDates:buildGradeDates('2025-06-01',4),accumulatedThrough:'2026-02',accumulatedGross:6000,accumulatedSS:400,accumulatedWithheld:900,annualGrossOverride:30000,annualSSOverride:2000});
  state.months['2026-01']={...blankMonth(),actual:{gross:3000,ss:200,withheld:450,guardGross:1000,otherDeductions:0,net:2350,source:'Synthetic'}};
  const original=structuredClone(state),annual=yearCalculation(state,2026);
  expect(annual.recordedWithholding).toBe(900);
  expect(annual.months[1]).toMatchObject({allocated:true,cashGross:3000,cashSS:200,withheld:450});
  expect(annual.incomeTax).toMatchObject({gross:30000,ss:2000,liability:4584.12,withheld:annual.withheld});
  expect(annual.recordedWithholding+annual.forecastWithholding).toBeCloseTo(annual.withheld,2);
  expect(annual.net).toBeCloseTo(annual.months.reduce((n,m)=>n+m.net,0),2);
  state.settings.fiscalYear=2027;
  expect(yearCalculation(state,2026).incomeTax).toMatchObject({gross:annual.gross,ss:annual.ss});
  state.settings.fiscalYear=2026;expect(state).toEqual(original);
  state.settings.fiscalPreset=null;expect(yearCalculation(state,2026).incomeTax).toBeNull();
 });
});
