import {useCallback,useEffect,useRef,useState} from 'react';
import {App as NativeApp} from '@capacitor/app';
import {CalendarDays,Wallet,ChartNoAxesCombined,SlidersHorizontal,Calculator,ChevronLeft,ChevronRight,Plus,FileText,Download,RefreshCw,Settings2,ArrowUpRight,List,Calendar,ShieldCheck,X} from 'lucide-react';
import {blankMonth,type State,type Shift,type MonthInput,type Settings as ProfileSettings} from './domain/model';
import {calculate,addMonth,eur,gradeOn,monthName,shortDate,shiftGross,standardShiftHours,suggestedType,yearCalculation,round,shiftCentreLabel} from './domain/engine';
import {exportBackup,parseBackup} from './domain/backup';
import {repository,type SavedState,type HistoryEntry} from './services/repository';
import {calendarService,type CalendarStatus} from './services/calendar';
import {openDocument,saveDocument} from './services/documents';
import {toCsv} from './services/csv';
import {isNative} from './platform/device';
import {Profile} from './Profile';
import {Settings} from './Settings';
import {ShiftEditor,MonthEditor,ReceiptEditor} from './Editors';
import {CalendarPanel} from './CalendarPanel';
import {Simulation} from './Simulation';
import {Panel,Line,Notice,Empty,Modal,errorMessage,Check} from './ui';

type Tab='payroll'|'shifts'|'year'|'simulation'|'settings';
type Overlay={kind:'shift';shift:Shift}|{kind:'receipt'|'month'|'calendar'|'profile'|'history'}|{kind:'backup';backup:ReturnType<typeof parseBackup>};
const tabs:{id:Tab;label:string;icon:typeof Wallet}[]=[{id:'payroll',label:'Nómina',icon:Wallet},{id:'shifts',label:'Guardias',icon:CalendarDays},{id:'year',label:'Año',icon:ChartNoAxesCombined},{id:'simulation',label:'Simular',icon:Calculator},{id:'settings',label:'Ajustes',icon:SlidersHorizontal}];
const currentMonth=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Madrid',year:'numeric',month:'2-digit'}).format(new Date());

export default function App(){
 const [data,setData]=useState<SavedState|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [tab,setTab]=useState<Tab>('payroll'),[month,setMonth]=useState(currentMonth),[overlay,setOverlay]=useState<Overlay|null>(null),[history,setHistory]=useState<HistoryEntry[]>([]);
 const [status,setStatus]=useState<CalendarStatus>({connected:false,lastFetched:null,persistent:isNative()}),[calendarNews,setCalendarNews]=useState(0),[online,setOnline]=useState(navigator.onLine);
 const [shiftMode,setShiftMode]=useState<'paid'|'worked'>('paid'),[shiftView,setShiftView]=useState<'list'|'calendar'>('list');
 const dirtySettings=useRef(false);
 const onSettingsDirty=useCallback((dirty:boolean)=>{dirtySettings.current=dirty;},[]);
 function mayLeaveSettings(){return !dirtySettings.current||window.confirm('Hay ajustes sin guardar. ¿Descartar esos cambios?');}
 function navigate(next:Tab){if(next===live.current.tab)return;if(!mayLeaveSettings())return;dirtySettings.current=false;setTab(next);}
 useEffect(()=>{const protect=(e:BeforeUnloadEvent)=>{if(dirtySettings.current){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',protect);return()=>window.removeEventListener('beforeunload',protect);},[]);
 const live=useRef({data,overlay,tab,month,busy});live.current={data,overlay,tab,month,busy};
 const adopt=useCallback((next:SavedState)=>setData(old=>!old||next.revision>=old.revision?next:old),[]);
 const refreshStatus=useCallback(async()=>setStatus(await calendarService.getStatus()),[]);
 async function load(){setLoading(true);setError('');try{adopt(await repository.load());try{await refreshStatus();}catch{setNotice('Vuelve a conectar el enlace iCal desde Guardias. Tus importes y guardias se conservan.');}}catch(e){setError(errorMessage(e));}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 useEffect(()=>{const update=()=>setOnline(navigator.onLine);window.addEventListener('online',update);window.addEventListener('offline',update);return()=>{window.removeEventListener('online',update);window.removeEventListener('offline',update);};},[]);
 useEffect(()=>{if(!notice)return;const id=setTimeout(()=>setNotice(''),9000);return()=>clearTimeout(id);},[notice]);
 const autoCalendar=useCallback(async()=>{const l=live.current;if(!l.data?.state.settings.profileComplete||l.overlay||l.busy||l.tab==='settings'||document.visibilityState==='hidden')return;try{const result=await calendarService.read(Number(l.month.slice(0,4)));if(result){adopt(result);setCalendarNews(result.proposals.filter(p=>p.kind!=='unchanged').length);if(result.added)setNotice(`${result.added} guardias añadidas como pendientes.`);await refreshStatus();}}catch{setNotice('No se pudo actualizar el calendario. Puedes continuar sin conexión o volver a leerlo desde Guardias.');}},[adopt,refreshStatus]);
 useEffect(()=>{if(data?.state.settings.profileComplete)void autoCalendar();},[data?.state.settings.profileComplete,month,autoCalendar]);
 useEffect(()=>{const focus=()=>void autoCalendar();window.addEventListener('focus',focus);let alive=true;const nativeListener=isNative()?NativeApp.addListener('appStateChange',({isActive})=>{if(isActive&&alive)void autoCalendar();}):null;return()=>{alive=false;window.removeEventListener('focus',focus);void nativeListener?.then(h=>h.remove());};},[autoCalendar]);
 function closeOverlay(){const type=live.current.overlay?.kind;if(type&&['shift','receipt','month','profile'].includes(type)&&!window.confirm('¿Cerrar este formulario sin guardar los cambios?'))return;setOverlay(null);}
 useEffect(()=>{if(!isNative())return;const handle=NativeApp.addListener('backButton',()=>{if(live.current.overlay)closeOverlay();else if(live.current.tab!=='payroll')navigate('payroll');else void NativeApp.exitApp();});return()=>{void handle.then(h=>h.remove());};},[]);
 async function save(next:State,reason:string){if(!data)throw new Error('Datos no cargados.');setBusy(true);setError('');try{const result=await repository.save(next,data.revision,reason);adopt(result);setNotice('Cambios guardados en este dispositivo.');}finally{setBusy(false);}}
 async function run(work:()=>Promise<void>){setBusy(true);setError('');try{await work();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 async function importBackup(){await run(async()=>{const file=await openDocument(['application/json','.json']);if(!file)return;if(file.size>2_100_000)throw new Error('La copia supera 2 MB.');setOverlay({kind:'backup',backup:parseBackup(await file.text())});});}
 async function exportJson(){if(data)await run(()=>saveDocument(`mi-nomina-${new Date().toISOString().slice(0,10)}.json`,'application/json',exportBackup(data.state)));}
 async function openHistory(){await run(async()=>{setHistory(await repository.history());setOverlay({kind:'history'});});}
 const state=data?.state;
 const c=state?calculate(state,month):null;
 const input=state?.months[month]??blankMonth();
 async function saveMonth(m:MonthInput,reason:string){if(!state)return;await save({...state,months:{...state.months,[month]:m}},reason);setOverlay(null);}
 function newShift(date?:string){if(!state||!c)return;const at=date??`${shiftMode==='paid'?c.workedMonth:month}-01`,centre=state.settings.centres[0]?.id??'unassigned',type=suggestedType(at,centre,state.settings);setOverlay({kind:'shift',shift:{id:crypto.randomUUID(),date:at,centre,type,title:'Guardia',hours:standardShiftHours(centre,type,state.settings),hoursMode:'standard',located:false,customRate:null,gradeOverride:null,status:'confirmed',sourceKey:'',sourceSignature:'',sourceCalendar:'',sourceNote:'Añadida manualmente'}});}
 async function exportCsv(annual=false){if(!state||!c)return;let rows:(string|number|null)[][];if(annual){const a=yearCalculation(state,Number(month.slice(0,4)));rows=[['Mes de cobro','Origen','Bruto','Cotizaciones','IRPF','Otros descuentos','Neto'],...a.months.map(m=>[m.month,m.actual?'Recibido':m.allocated?'Reparto del acumulado':'Estimado',m.cashGross,m.cashSS,m.withheld,m.otherDeductions,m.net])];}else{rows=[['Mes de cobro','Mes trabajado','Origen','Bruto','Cotizaciones','IRPF','Otros descuentos','Neto'],[month,c.workedMonth,c.actual?'Recibido':c.allocated?'Reparto del acumulado':'Estimado',c.cashGross,c.cashSS,c.withheld,c.otherDeductions,c.net],[],['Fecha','Descripción','Centro','Estado','Horas','Bruto'],...state.shifts.filter(s=>s.date.startsWith(c.workedMonth)).map(s=>[s.date,s.title,shiftCentreLabel(s,state.settings),s.status,s.hours,shiftGross(s,state.settings)])];}await run(()=>saveDocument(`mi-nomina-${annual?month.slice(0,4):month}.csv`,'text/csv',toCsv(rows)));}
 function renderOverlay(){if(!overlay||!state||!data)return null;
 if(overlay.kind==='shift')return <Modal title="Revisar guardia" onClose={closeOverlay}><ShiftEditor initial={overlay.shift} state={state} busy={busy} onSave={async shift=>{await save({...state,shifts:state.shifts.some(s=>s.id===shift.id)?state.shifts.map(s=>s.id===shift.id?shift:s):[...state.shifts,shift]},'Edición de guardia');setOverlay(null);}}/></Modal>;
 if(overlay.kind==='receipt')return <Modal title="Revisar nómina recibida" onClose={closeOverlay}><ReceiptEditor state={state} month={month} initial={input} busy={busy} onSave={m=>saveMonth(m,'Recibo revisado')}/></Modal>;
 if(overlay.kind==='month')return <Modal title="Extras y ajustes del mes" onClose={closeOverlay}><MonthEditor initial={input} busy={busy} onSave={m=>saveMonth(m,'Ajustes mensuales')}/></Modal>;
 if(overlay.kind==='profile')return <Modal title="Tu residencia" onClose={closeOverlay}><Profile initial={state.settings} busy={busy} onSave={async s=>{await save({...state,settings:s},'Perfil de residencia');setOverlay(null);}}/></Modal>;
 if(overlay.kind==='calendar')return <Modal title="Importar y revisar calendario" onClose={()=>setOverlay(null)}><CalendarPanel year={Number(month.slice(0,4))} state={state} status={status} onStatus={refreshStatus} onSaved={d=>{adopt(d);setCalendarNews(0);}}/></Modal>;
 if(overlay.kind==='backup')return <Modal title="Revisar copia antes de restaurar" onClose={()=>setOverlay(null)}><p>{overlay.backup.summary.shifts} guardias · {overlay.backup.summary.receipts} meses con recibos.</p>{overlay.backup.warnings.map(w=><Notice key={w}>{w}</Notice>)}<Notice>La copia sustituirá tus datos actuales. Se conservará una versión recuperable en el historial. El enlace iCal permanece separado.</Notice><button className="primary" disabled={busy} onClick={()=>void run(async()=>{await save(overlay.backup.state,'Restauración de copia JSON');setOverlay(null);})}>Restaurar esta copia</button></Modal>;
 return <Modal title="Versiones anteriores" onClose={()=>setOverlay(null)}><p className="muted">Restaurar también crea una versión recuperable.</p>{!history.length&&<Empty>Aún no hay versiones anteriores.</Empty>}{history.map(h=><div className="history-row" key={h.revision}><div><strong>{new Date(h.savedAt).toLocaleString('es-ES')}</strong><p className="muted">Antes de: {h.reason}</p></div><button disabled={busy} onClick={()=>{if(window.confirm('¿Restaurar esta versión? Tus datos actuales quedarán en el historial.'))void run(async()=>{adopt(await repository.restore(h.revision,data.revision));setOverlay(null);setNotice('Versión restaurada.');});}}>Restaurar</button></div>)}</Modal>;
 }
 const alerts=<>{error&&<div className="global-error" role="alert"><span>{error}</span><button className="icon-button" aria-label="Cerrar error" onClick={()=>setError('')}><X size={18}/></button></div>}{notice&&<div className="toast" role="status">{notice}</div>}</>;
 if(loading||!state||!c)return <main className="loading-screen"><div className="wordmark">Mi nómina</div>{loading?<p role="status">Abriendo tus datos locales…</p>:<><p role="alert">{error}</p><button onClick={()=>void load()}>Volver a intentar</button><p className="muted">No se han borrado ni reiniciado tus datos.</p></>}</main>;
 if(!state.settings.profileComplete)return <><Profile initial={state.settings} busy={busy} onSave={s=>save({...state,settings:s},'Alta inicial')} onImport={()=>void importBackup()}/>{renderOverlay()}{alerts}</>;
 const grade=gradeOn(`${month}-15`,state.settings),worked=shiftMode==='paid'?c.workedMonth:month,shifts=state.shifts.filter(s=>s.date.startsWith(worked)).sort((a,b)=>a.date.localeCompare(b.date)),closed=state.closedShiftMonths.includes(worked);
 const badge=c.actual?'Recibido':c.allocated?'Reparto del acumulado':'Estimado';
 return <div className="app-shell"><header className="topbar"><div className="wordmark">Mi nómina<span>{grade?`R${grade} · `:''}MIR SERMAS</span></div><span className="local-indicator"><span className="status-dot"/>{online?'Datos locales':'Sin conexión'}</span></header>
 <main className="workspace"><div className="page-heading"><div><p className="eyebrow">{tab==='payroll'?'Tu mes de cobro':tab==='shifts'?'Tu actividad':tab==='year'?'Tu previsión anual':tab==='simulation'?'Tus escenarios':'Tu calculadora'}</p><h1>{tabs.find(t=>t.id===tab)?.label}</h1></div>{tab!=='settings'&&<div className="month-control"><button aria-label="Mes anterior" className="icon-button" disabled={month<='2000-01'} onClick={()=>setMonth(addMonth(month,-1))}><ChevronLeft size={20}/></button><input aria-label="Mes de cobro seleccionado" type="month" min="2000-01" max="2099-12" value={month} onChange={e=>{if(/^20\d{2}-(0[1-9]|1[0-2])$/.test(e.target.value))setMonth(e.target.value);}}/><button aria-label="Mes siguiente" className="icon-button" disabled={month>='2099-12'} onClick={()=>setMonth(addMonth(month,1))}><ChevronRight size={20}/></button></div>}</div>
 {!isNative()&&<p className="preview-note">Vista de navegador · datos separados de la app Android</p>}
 {tab==='payroll'&&<div className="stack"><section className="net-card"><div className="section-title"><span className="badge">{badge}</span><span className="muted">{monthName(month)}</span></div><p className="net-label">Neto {c.actual?'recibido':'previsto'}</p><div className="net-amount">{eur(c.net)}</div><div className="net-footer"><span>Guardias de {monthName(c.workedMonth)}</span><span>{c.actual?'Importes confirmados':`${c.percent.toLocaleString('es-ES')} % IRPF`}</span></div></section><div className="metric-row"><div><small>Bruto mensual</small><strong>{eur(c.cashGross)}</strong></div><div><small>Guardias previstas</small><strong>{eur(c.guards.gross)}</strong></div></div>
 <Panel title="De bruto a neto"><Line label="Sueldo y complemento previstos" value={c.fixed}/><Line label="Guardias previstas" value={c.guards.gross}/>{!!c.extra&&<Line label="Paga extra prevista" value={c.extra}/>} {!!c.vacation&&<Line label="Promedio vacacional" value={c.vacation}/>} {!!c.other&&<Line label="Otros brutos" value={c.other}/>}<Line label={c.actual?'Bruto del recibo':'Bruto total'} value={c.cashGross} strong/><Line label="Cotizaciones" value={-c.cashSS}/><Line label="IRPF retenido" value={-c.withheld}/>{!!c.otherDeductions&&<Line label="Otros descuentos" value={-c.otherDeductions}/>}<Line label="Neto" value={c.net} strong/>{c.actual&&<Notice>El desglose salarial superior es la previsión. El bruto y las deducciones finales son los del recibo confirmado.</Notice>}<button onClick={()=>setOverlay({kind:'month'})}><Settings2 size={18}/>Extras y ajustes</button></Panel>
 <Panel title={c.actual?'Tu recibo confirmado':'Comprueba tu nómina'} action={<FileText size={20}/>}><p className="muted">{c.actual?'Conserva sus importes aunque cambien tus previsiones.':'Lee un PDF o introduce los importes para compararlos con esta previsión.'}</p>{c.actual&&<><Line label="Neto previsto" value={c.forecastNet}/><Line label="Diferencia recibida" value={round(c.net-c.forecastNet)}/></>}<button className="primary" onClick={()=>setOverlay({kind:'receipt'})}>{c.actual?'Revisar recibo':'Añadir recibo'}</button></Panel>
 {!!c.warnings.length&&<details className="panel warnings"><summary>{c.warnings.length} puntos para revisar</summary><ul>{c.warnings.map(w=><li key={w}>{w}</li>)}</ul></details>}<button onClick={()=>void exportCsv()} disabled={busy}><Download size={18}/>Exportar detalle CSV</button></div>}
 {tab==='shifts'&&<div className="stack"><div className="segmented"><button aria-pressed={shiftMode==='paid'} onClick={()=>setShiftMode('paid')}>Por mes de cobro</button><button aria-pressed={shiftMode==='worked'} onClick={()=>setShiftMode('worked')}>Por mes trabajado</button></div><div className="section-title"><div><h2>{monthName(worked)}</h2><p className="muted">{shifts.length} guardias · {shifts.filter(s=>s.status==='pending').length} pendientes</p></div><button className="primary" onClick={()=>newShift()}><Plus size={18}/>Añadir</button></div><div className="actions"><button onClick={()=>setOverlay({kind:'calendar'})}><RefreshCw size={18}/>Calendario{calendarNews>0?` (${calendarNews})`:''}</button><button aria-label={shiftView==='list'?'Ver calendario mensual':'Ver lista de guardias'} onClick={()=>setShiftView(shiftView==='list'?'calendar':'list')}>{shiftView==='list'?<Calendar size={18}/>:<List size={18}/>} {shiftView==='list'?'Ver mes':'Ver lista'}</button></div>
 {shiftView==='calendar'?<ShiftMonth month={worked} shifts={shifts} onShift={s=>setOverlay({kind:'shift',shift:s})} onAdd={newShift}/>:<div className="shift-list">{shifts.map(s=><button className={`shift-row ${s.status}`} key={s.id} onClick={()=>setOverlay({kind:'shift',shift:s})}><div className="shift-date"><strong>{s.date.slice(8)}</strong><span>{new Date(`${s.date}T12:00:00Z`).toLocaleDateString('es-ES',{weekday:'short',timeZone:'UTC'})}</span></div><div className="shift-description"><strong>{s.title}</strong><small>{shiftCentreLabel(s,state.settings)} · {s.hours} h</small><span className="badge">{s.status==='confirmed'?'Revisada':s.status==='excluded'?'Excluida':'Pendiente'}</span></div><div className="shift-amount">{eur(shiftGross(s,state.settings))}<ArrowUpRight size={16}/></div></button>)}{!shifts.length&&<Empty action={<button onClick={()=>newShift()}><Plus size={18}/>Añadir primera guardia</button>}>No hay guardias registradas este mes.</Empty>}</div>}
 <Check label="Mes trabajado completo" checked={closed} onChange={v=>void run(()=>save({...state,closedShiftMonths:v?[...state.closedShiftMonths,worked]:state.closedShiftMonths.filter(m=>m!==worked)},'Cierre de mes trabajado'))} hint="Márcalo cuando estén todas. Si no hay guardias, un mes completo cuenta como cero y no usa el patrón."/><Notice>La tarifa depende del día trabajado; el cobro se desplaza {state.settings.payDelay} mes(es). Las excluidas se conservan para impedir que vuelvan a entrar por una reimportación.</Notice></div>}
 {tab==='year'&&<Annual state={state} year={Number(month.slice(0,4))} onMonth={m=>{setMonth(m);setTab('payroll');}} onExport={()=>void exportCsv(true)}/>}
 {tab==='simulation'&&<Simulation state={state} month={month}/>}
 {/* Calendar writes must not remount an open settings draft. */}
 {tab==='settings'&&<Settings key={JSON.stringify(state.settings)} state={state} busy={busy} onSave={s=>save({...state,settings:s},'Reglas y centros')} onDirty={onSettingsDirty} onProfile={()=>{if(mayLeaveSettings())setOverlay({kind:'profile'});}} onExport={()=>void exportJson()} onImport={()=>{if(mayLeaveSettings())void importBackup();}} onHistory={()=>{if(mayLeaveSettings())void openHistory();}}/>}
 <p className="workspace-footer"><ShieldCheck size={14}/>Estimación orientativa · Contrasta tu recibo</p></main><nav className="bottom-nav" aria-label="Navegación principal">{tabs.map(({id,label,icon:Icon})=><button key={id} aria-current={tab===id?'page':undefined} onClick={()=>navigate(id)}><Icon size={21}/><span>{label}</span></button>)}</nav>{renderOverlay()}{alerts}</div>;
}

function Annual({state,year,onMonth,onExport}:{state:State;year:number;onMonth:(m:string)=>void;onExport:()=>void}){const annual=yearCalculation(state,year),max=Math.max(1,...annual.months.map(m=>m.net));return <div className="stack"><section className="net-card"><span className="badge">Recibido + estimado</span><p className="net-label">Neto anual · {year}</p><div className="net-amount annual-amount">{eur(annual.net)}</div><p className="muted">{annual.actualMonths} meses con recibo confirmado</p></section><div className="annual-bars" role="img" aria-label={`Previsión neta por mes del año ${year}; detalle disponible en las filas siguientes.`}>{annual.months.map(m=><button key={m.month} className={m.actual?'actual':''} onClick={()=>onMonth(m.month)} aria-label={`${monthName(m.month)}: ${eur(m.net)}`}><span style={{height:`${Math.max(1,m.net/max*100)}%`}}/><small>{monthName(m.month).slice(0,3)}</small></button>)}</div><div className="legend"><span>Recibido</span><span>Estimado / acumulado</span></div><Panel title="Resumen anual"><Line label="Bruto" value={annual.gross}/><Line label="Cotizaciones" value={annual.ss}/><Line label="IRPF retenido / previsto" value={annual.withheld}/><Line label="Otros descuentos" value={annual.otherDeductions}/><Line label="Neto" value={annual.net} strong/></Panel><div className="annual-list">{annual.months.map(m=><button key={m.month} onClick={()=>onMonth(m.month)}><span>{monthName(m.month)}<small>{m.actual?'Recibido':m.allocated?'Reparto de acumulado':'Estimado'}</small></span><strong>{eur(m.net)}</strong><ChevronRight size={16}/></button>)}</div><button onClick={onExport}><Download size={18}/>Exportar año CSV</button><Notice>Los meses sin recibo son previsiones o repartos orientativos del acumulado. Los importes fiscales manuales no crean cobros.</Notice></div>;}
function ShiftMonth({month,shifts,onShift,onAdd}:{month:string;shifts:Shift[];onShift:(s:Shift)=>void;onAdd:(d:string)=>void}){const [year,m]=month.split('-').map(Number),days=new Date(Date.UTC(year,m,0)).getUTCDate(),offset=(new Date(`${month}-01T12:00:00Z`).getUTCDay()+6)%7;return <div className="calendar-grid">{['L','M','X','J','V','S','D'].map(d=><span className="weekday" key={d}>{d}</span>)}{Array.from({length:offset},(_,i)=><div key={`empty-${i}`}/>)}{Array.from({length:days},(_,i)=>{const date=`${month}-${String(i+1).padStart(2,'0')}`,items=shifts.filter(s=>s.date===date);return <div className="day" key={date}><button className="day-number" aria-label={`Añadir guardia el ${shortDate(date)}`} onClick={()=>onAdd(date)}>{i+1}</button>{items.map(s=><button key={s.id} className={`day-shift ${s.status}`} onClick={()=>onShift(s)} aria-label={`${s.title}, ${s.hours} horas`}>{s.hours}h</button>)}</div>;})}</div>;}
