import {useState} from 'react';
import {FileUp,Link,RefreshCw,Unlink} from 'lucide-react';
import {type Proposal} from './domain/calendar';
import {type State} from './domain/model';
import {type CalendarRead,type CalendarStatus,calendarService} from './services/calendar';
import {openDocument} from './services/documents';
import {type SavedState} from './services/repository';
import {eur,shortDate,shiftGross,shiftCentreLabel} from './domain/engine';
import {Field,Notice,ErrorText,errorMessage} from './ui';

const kindNames:Record<Proposal['kind'],string>={new:'Nueva',modified:'Modificada',cancelled:'Cancelada',missing:'No encontrada',manualMatch:'Coincide con una manual',ambiguous:'Revisar coincidencia',unchanged:'Sin cambios'};
export function CalendarPanel({year,state,status,onStatus,onSaved}:{year:number;state:State;status:CalendarStatus;onStatus:()=>Promise<void>;onSaved:(d:SavedState)=>void}){
 const [url,setUrl]=useState(''),[reading,setReading]=useState(false),[error,setError]=useState(''),[review,setReview]=useState<CalendarRead|null>(null),[done,setDone]=useState('');
 async function run(read:()=>Promise<CalendarRead|null>){setError('');setDone('');setReading(true);try{const result=await read();if(result){setReview(result);onSaved(result);}await onStatus();}catch(e){setError(errorMessage(e));}finally{setReading(false);}}
 async function file(){await run(async()=>{const f=await openDocument(['text/calendar','.ics']);if(!f)return null;if(f.size>2_000_000)throw new Error('El calendario supera 2 MB.');return calendarService.importFile(await f.text(),year);});}
 function change(index:number,action:Proposal['action']){if(review)setReview({...review,proposals:review.proposals.map((p,i)=>i===index?{...p,action}:p)});}
 return <div className="stack"><Notice>Se revisan eventos de {year} y cruces de ejercicio necesarios para el cobro. Torrelodones laborable: 11 h; el resto usa el horario habitual de hospital. Importar un archivo parcial nunca demuestra una cancelación.</Notice><button onClick={()=>void file()} disabled={reading}><FileUp size={18}/>Importar archivo ICS</button>
 <details><summary>Conectar Google Calendar por enlace</summary><Field label="Dirección secreta iCal" hint="Google Calendar → Configuración → Integrar calendario. No se incluye en las copias JSON."><input type="password" autoComplete="off" spellCheck={false} placeholder="https://calendar.google.com/calendar/ical/…" value={url} onChange={e=>setUrl(e.target.value)}/></Field><button disabled={reading||!url} onClick={()=>void run(async()=>{const result=await calendarService.connect(url,year);setUrl('');return result;})}><Link size={18}/>Conectar y revisar</button>{!status.persistent&&<p className="muted">En la WebApp recomendamos importar un archivo ICS: el navegador puede bloquear la lectura del enlace. Si funciona, el enlace solo se conserva durante la sesión. Android lo guarda cifrado.</p>}</details>
 {status.connected&&<div className="stack"><p className="muted">{status.lastFetched?`Última lectura: ${new Date(status.lastFetched).toLocaleString('es-ES')}`:'Calendario conectado'}</p><div className="actions"><button disabled={reading} onClick={()=>void run(()=>calendarService.read(year,{force:true,autoAdd:false}))}><RefreshCw size={18}/>Leer cambios</button><button disabled={reading} onClick={async()=>{try{await calendarService.disconnect();setReview(null);await onStatus();setDone('Enlace desconectado. Las guardias se conservan.');}catch(e){setError(errorMessage(e));}}}><Unlink size={18}/>Desconectar</button></div></div>}
 {reading&&<p role="status">Leyendo calendario…</p>}<ErrorText error={error}/>{done&&<p role="status" className="success">{done}</p>}
 {review&&<><h3>Revisión antes de guardar</h3>{review.notes.map(n=><p className="muted" key={n}>{n}</p>)}{review.proposals.filter(p=>p.kind!=='unchanged').length===0&&<p>No hay cambios pendientes.</p>}{review.proposals.map((p,i)=>{if(p.kind==='unchanged')return null;const s=p.incoming??p.current;return <article className="proposal" key={p.id}><span className="badge">{kindNames[p.kind]}</span><h3>{s?.title??'Evento de calendario'}</h3>{s&&<p>{shortDate(s.date)} · {shiftCentreLabel(s,state.settings)} · {s.hours} h · {eur(shiftGross(s,state.settings))} estimados</p>}<p className="muted break-word">{p.detail}</p>{p.kind==='ambiguous'&&<p className="muted">Revisa la coincidencia antes de incorporar este evento.</p>}<Field label={`Decisión: ${s?.title??p.id}`}><select value={p.action} onChange={e=>change(i,e.target.value as Proposal['action'])}><option value="keep">{p.existingId?'Conservar sin cambios':'Omitir esta vez'}</option>{p.incoming&&!p.existingId&&<option value="add">{p.incoming.status==='excluded'?'Conservar como excluida':'Añadir pendiente'}</option>}{p.existingId&&p.incoming&&<option value="link">Vincular conservando ajustes</option>}{p.existingId&&p.incoming&&<option value="update">Actualizar con los datos del calendario</option>}{p.existingId&&<option value="exclude">Excluir sin borrar</option>}</select></Field>{p.action==='update'&&<Notice>Esta decisión sustituye las horas y ajustes de esa guardia por los datos del evento.</Notice>}</article>;})}<button className="primary" disabled={reading} onClick={async()=>{setReading(true);setError('');try{const result=await calendarService.commit(review.proposals,review.revision);onSaved(result);setReview(null);setDone(`${result.added} añadidas · ${result.updated} actualizadas · ${result.linked} vinculadas · ${result.excluded} excluidas`);}catch(e){setError(errorMessage(e));}finally{setReading(false);}}}>Guardar decisiones</button></>}
 </div>;
}
