import {useState} from 'react';
import {FileUp,Plus,Trash2} from 'lucide-react';
import {type State,type Shift,type MonthInput,type Actual,shiftSchema,monthSchema,actualSchema} from './domain/model';
import {eur,round,shiftGross,rateFor,updateShiftSchedule,standardShiftHours,classifyShiftDay,monthName,shiftCentreLabel} from './domain/engine';
import {openDocument,readPdf} from './services/documents';
import {Field,NumberField,Check,Line,Notice,SafeForm,Submit,ErrorText,errorMessage,typeNames} from './ui';

export function ShiftEditor({initial,state,busy,onSave}:{initial:Shift;state:State;busy:boolean;onSave:(s:Shift)=>Promise<void>}){
 const [s,set]=useState(initial),[error,setError]=useState('');
 const schedule=(patch:Partial<Pick<Shift,'date'|'centre'|'type'>>)=>set(updateShiftSchedule(s,patch,state.settings));
 const classification=classifyShiftDay(s.date,s.centre,state.settings);
 return <SafeForm onSubmit={async()=>{try{setError('');if(s.status==='confirmed'&&s.centre!=='unassigned'&&!state.settings.centres.some(c=>c.id===s.centre))throw new Error('Selecciona un centro válido o el horario de hospital.');await onSave(shiftSchema.parse(s));}catch(e){setError(errorMessage(e));}}}>
 <Field label="Fecha trabajada"><input required type="date" value={s.date} onChange={e=>{if(e.target.value)schedule({date:e.target.value});}}/></Field>
 <Field label="Centro (opcional)"><select value={s.centre} onChange={e=>schedule({centre:e.target.value})}>{!state.settings.centres.some(c=>c.id===s.centre)&&<option value={s.centre}>{shiftCentreLabel(s,state.settings)}</option>}{state.settings.centres.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}{s.centre!=='unassigned'&&<option value="unassigned">Horario de hospital / según descripción</option>}</select></Field>
 <Field label="Descripción"><input required maxLength={180} value={s.title} onChange={e=>set({...s,title:e.target.value,...(s.hoursMode==='standard'?{hours:standardShiftHours(s.centre,s.type,state.settings,e.target.value)}:{})})}/></Field>
 <Field label="Tipo de día"><select value={s.type} onChange={e=>schedule({type:e.target.value as Shift['type']})}>{Object.entries(typeNames).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></Field><p className="muted">{classification.reason}</p>
 <Check label="Usar horario habitual de guardia" checked={s.hoursMode==='standard'} onChange={v=>set({...s,hoursMode:v?'standard':'custom',hours:v?standardShiftHours(s.centre,s.type,state.settings,s.title):s.hours})}/>
 <NumberField label="Horas abonables" value={s.hours} min={.25} max={48} onChange={v=>set({...s,hours:v??0,hoursMode:'custom'})} hint="Las horas manuales se conservan al cambiar el centro o la fecha."/>
 <Field label="Estado"><select value={s.status} onChange={e=>set({...s,status:e.target.value as Shift['status']})}><option value="confirmed">Revisada</option><option value="pending">Pendiente</option><option value="excluded">Excluida</option></select></Field>
 <details><summary>Tarifa y año manuales</summary><NumberField label="Tarifa manual (€/h)" nullable min={0} max={200} value={s.customRate} onChange={v=>set({...s,customRate:v})} hint="Vacío: tabla por fecha trabajada. Una tarifa manual ya incluye cualquier ajuste por localización."/><Field label="Año de residencia"><select value={s.gradeOverride??''} onChange={e=>set({...s,gradeOverride:e.target.value?Number(e.target.value):null})}><option value="">Según fecha trabajada</option>{[1,2,3,4,5].map(n=><option key={n} value={n}>R{n}</option>)}</select></Field><Check label="Guardia localizada" checked={s.located} onChange={v=>set({...s,located:v})} hint="Propuesta del 50 % de la tarifa física; contrasta el criterio de tu centro."/></details>
 <div className="subtotal"><Line label={`${eur(rateFor(s,state.settings))}/h`} value={shiftGross(s,state.settings)} strong/></div>{s.sourceNote&&<p className="muted">{s.sourceNote}</p>}<ErrorText error={error}/><Submit busy={busy}>Guardar guardia</Submit>
 </SafeForm>;
}

export function MonthEditor({initial,busy,onSave}:{initial:MonthInput;busy:boolean;onSave:(m:MonthInput)=>Promise<void>}){
 const [m,set]=useState(structuredClone(initial)),[error,setError]=useState('');
 const fields:[keyof MonthInput,string][]=[['vacationDays','Días de vacaciones'],['vacationOverride','Promedio vacacional manual (€)'],['extraOverride','Paga extra manual (€)'],['otherGross','Otros brutos / atrasos (€)'],['guardGrossOverride','Total bruto de guardias manual (€)'],['ssOverride','Cotizaciones manuales (€)'],['taxOverride','IRPF del mes (%)']];
 return <SafeForm onSubmit={async()=>{try{setError('');await onSave(monthSchema.parse(m));}catch(e){setError(errorMessage(e));}}}><Notice>Un campo vacío conserva el cálculo automático. Un 0 fija el importe en cero. El total manual de guardias sustituye su suma.</Notice>{fields.map(([k,label])=><NumberField key={k} label={label} value={m[k] as number|null} nullable={!['vacationDays','otherGross'].includes(k)} min={0} max={k==='taxOverride'?47:k==='vacationDays'?31:1000000} onChange={v=>set({...m,[k]:v})}/>)}<ErrorText error={error}/><Submit busy={busy}>Guardar ajustes del mes</Submit></SafeForm>;
}

type ReceiptValues={gross:number|null;ss:number|null;withheld:number|null;guardGross:number|null;otherDeductions:number|null;net:number|null};
type DocDraft=ReceiptValues&{hash:string;name:string;paymentMonth:string|null;warnings:string[];acknowledged:boolean};
const receiptFields:[keyof ReceiptValues,string][]=[['gross','Total bruto (€)'],['ss','Cotizaciones (€)'],['withheld','IRPF retenido (€)'],['guardGross','Guardias incluidas en el bruto (€)'],['otherDeductions','Otros descuentos (€)'],['net','Neto recibido (€)']];
export function ReceiptEditor({state,month,initial,busy,onSave}:{state:State;month:string;initial:MonthInput;busy:boolean;onSave:(m:MonthInput)=>Promise<void>}){
 const a=initial.actual;
 const [values,setValues]=useState<ReceiptValues>(a??{gross:null,ss:null,withheld:null,guardGross:null,otherDeductions:0,net:null});
 const [source,setSource]=useState(a?.source??''),[docs,setDocs]=useState<DocDraft[]>([]),[mode,setMode]=useState<'replace'|'add'>('replace'),[reading,setReading]=useState(false),[error,setError]=useState(''),[remove,setRemove]=useState(false);
 async function importPdf(){setReading(true);setError('');try{const file=await openDocument(['application/pdf']);if(!file)return;const d=await readPdf(file);if(docs.some(v=>v.hash===d.hash)||Object.values(state.months).some(v=>v.receiptHashes.includes(d.hash)))throw new Error('Este PDF ya está registrado o seleccionado.');setDocs([...docs,{...d,otherDeductions:d.otherDeductions??0,acknowledged:d.paymentMonth===month}]);}catch(e){setError(errorMessage(e));}finally{setReading(false);}}
 function fields(v:ReceiptValues,change:(v:ReceiptValues)=>void,prefix=''){return receiptFields.map(([k,label])=><NumberField key={k} label={prefix+label} value={v[k]} min={k==='net'?-100000:0} max={1000000} onChange={n=>change({...v,[k]:n})}/>);}
 return <SafeForm onSubmit={async()=>{try{setError('');let actual:Actual;let hashes=initial.receiptHashes;
 if(docs.length){if(docs.some(d=>!d.acknowledged))throw new Error('Confirma el mes de los documentos que no coinciden.');const parsed=docs.map(d=>actualSchema.parse({...d,source:'PDF revisado'}));const base=mode==='add'&&a?a:{gross:0,ss:0,withheld:0,guardGross:0,otherDeductions:0,net:0,source:''};const totals={...base};for(const r of parsed)for(const [k] of receiptFields)totals[k]=round(totals[k]+r[k]);actual=actualSchema.parse({...totals,source:source||`${parsed.length} documento(s) revisado(s)`});hashes=[...(mode==='add'?initial.receiptHashes:[]),...docs.map(d=>d.hash)];}
 else{actual=actualSchema.parse({...values,source});}
 await onSave(monthSchema.parse({...initial,actual,receiptHashes:hashes}));}catch(e){setError(errorMessage(e));}}}>
 <p className="muted">Mes de cobro: {monthName(month)}. Puedes sumar una nómina ordinaria y atrasos del mismo mes.</p><button type="button" className="secondary" disabled={reading||busy} onClick={()=>void importPdf()}><FileUp size={18}/>{reading?'Leyendo documento…':docs.length?'Añadir otro PDF':'Leer PDF de nómina'}</button><p className="muted">El documento se lee aquí y no se conserva. Escaneados o formatos no reconocidos: introduce los importes manualmente.</p>
 {docs.length>0?<><Field label="Cómo incorporar los PDF"><select value={mode} onChange={e=>setMode(e.target.value as 'replace'|'add')}><option value="replace">Sustituir el total del mes</option>{a&&<option value="add">Sumar al total registrado</option>}</select></Field>{docs.map((d,i)=><section className="document-draft" key={d.hash}><div className="section-title"><h3>Documento {i+1}</h3><button type="button" className="icon-button" aria-label={`Quitar documento ${i+1}`} onClick={()=>setDocs(docs.filter((_,j)=>j!==i))}><Trash2 size={18}/></button></div><p className="muted break-word">{d.name}</p>{d.warnings.map(w=><p key={w} className="muted">{w}</p>)}<p>Periodo detectado: {d.paymentMonth?monthName(d.paymentMonth):'Sin identificar'}</p>{fields(d,v=>setDocs(docs.map((old,j)=>j===i?{...old,...v}:old)),`Documento ${i+1}: `)}{d.paymentMonth!==month&&<Check label={`Asignar este documento a ${monthName(month)}`} checked={d.acknowledged} onChange={v=>setDocs(docs.map((old,j)=>j===i?{...old,acknowledged:v}:old))}/>}</section>)}</>:<>{fields(values,setValues)}<button type="button" className="text-button" onClick={()=>setValues({...values,net:round((values.gross??0)-(values.ss??0)-(values.withheld??0)-(values.otherDeductions??0))})}><Plus size={16}/>Proponer neto a partir del desglose</button></>}
 <Field label="Referencia (sin datos personales)"><input maxLength={250} placeholder="Ordinaria, atrasos…" value={source} onChange={e=>setSource(e.target.value)}/></Field><Notice>El neto que confirmes se conserva. Los otros descuentos no se suman a Seguridad Social.</Notice><ErrorText error={error}/><Submit busy={busy||reading}>Guardar recibo revisado</Submit>
 {a&&<div className="danger-zone">{remove?<><p>Se quitará el recibo y volverá la previsión. Podrás recuperarlo desde el historial.</p><button type="button" disabled={busy} onClick={()=>void onSave({...initial,actual:null,receiptHashes:[]}).catch(e=>setError(errorMessage(e)))}>Confirmar retirada del recibo</button><button type="button" onClick={()=>setRemove(false)}>Conservar recibo</button></>:<button type="button" onClick={()=>setRemove(true)}>Retirar recibo de este mes</button>}</div>}
 </SafeForm>;
}
