import {useEffect,useState} from 'react';
import {Download,FileUp,History,Plus,UserRound,ExternalLink as LinkIcon} from 'lucide-react';
import {type State,type Settings as SettingsType,settingsSchema} from './domain/model';
import {CentreEditor} from './CentreEditor';
import {workProfileLabel} from './WorkProfiles';
import {ruleSets} from './domain/rules';
import licenses from './third-party-licenses.txt?raw';
import {version} from '../package.json';
import {Field,NumberField,Check,Notice,Panel,SafeForm,Submit,ErrorText,errorMessage,ExternalLink,typeNames} from './ui';

export function Settings({state,busy,onSave,onProfile,onWorkProfiles,onExport,onImport,onHistory,onDirty}:{state:State;busy:boolean;onSave:(s:SettingsType)=>Promise<void>;onProfile:()=>void;onWorkProfiles:()=>void;onExport:()=>void;onImport:()=>void;onHistory:()=>void;onDirty:(dirty:boolean)=>void}){
 const [s,set]=useState(structuredClone(state.settings)),[error,setError]=useState(''),[saved,setSaved]=useState(false);
 const dirty=JSON.stringify(s)!==JSON.stringify(state.settings);
 useEffect(()=>{onDirty(dirty);return()=>onDirty(false);},[dirty,onDirty]);
 function change<K extends keyof SettingsType>(key:K,value:SettingsType[K]){set({...s,[key]:value});setSaved(false);}
 const numeric=(key:keyof SettingsType,label:string,hint?:string,nullable=false)=><NumberField key={key} label={label} hint={hint} nullable={nullable} value={s[key] as number|null} onChange={v=>change(key,v as never)}/>;
 return <div className="stack"><Panel title="Tu residencia" action={<UserRound size={20}/>}><p>Inicio: {s.residencyStart.split('-').reverse().join('/')}<br/>Fin previsto: {s.residencyEnd?.split('-').reverse().join('/')??'Por completar'}</p><button onClick={onProfile}>Editar perfil y cambios R1–R5</button></Panel>
 <Panel title="Perfiles de condiciones"><p>{workProfileLabel(state.settings)}</p><p className="muted">Elige MFyC · FJD con calendario y fiscalidad de Madrid o guarda tus propias condiciones.</p><button onClick={onWorkProfiles}>Seleccionar o crear perfil</button></Panel>
 <SafeForm onSubmit={async()=>{try{setError('');await onSave(settingsSchema.parse(s));setSaved(true);}catch(e){setError(errorMessage(e));}}}>
 <details className="panel" open><summary>Centros y festivos locales</summary><p className="muted">Cada centro conserva su municipio físico y puede usar el calendario de otro municipio. Introduce los festivos del calendario elegido; un año vacío queda pendiente de revisión.</p>{s.centres.map((c,i)=><CentreEditor key={c.id} centre={c} onChange={v=>change('centres',s.centres.map((old,j)=>j===i?v:old))} canRemove={!state.shifts.some(v=>v.centre===c.id)&&(!!c.archived||s.centres.filter(centre=>!centre.archived).length>1)} onRemove={()=>change('centres',s.centres.filter((_,j)=>j!==i))}/>)}<button type="button" onClick={()=>change('centres',[...s.centres,{id:crypto.randomUUID(),name:'',municipality:'',labourHours:17,festiveHours:24,aliases:[],localHolidays:{}}])}><Plus size={18}/>Añadir centro</button></details>
 <details className="panel"><summary>Sueldo, guardias y vacaciones</summary>{numeric('salaryBase','Sueldo base mensual (€)')}{s.complements.map((v,i)=><NumberField key={i} label={`Complemento R${i+1} (€)`} value={v} onChange={n=>change('complements',s.complements.map((a,j)=>i===j?n??0:a))}/>)}{numeric('payDelay','Retraso del cobro de guardias (meses)')}{numeric('expectedLabour','Guardias laborables del patrón mensual')}{numeric('expectedFestive','Guardias festivas del patrón mensual')}{numeric('defaultLabourHours','Horas habituales de hospital en laborable','Para centros con horario general; Torrelodones laborable mantiene 11 h.')}{numeric('defaultFestiveHours','Horas habituales en sábado, domingo o festivo','Para centros con horario general. Cada centro puede tener un horario propio.')}{numeric('vacationDivisor','Divisor de vacaciones','22 días laborables es un supuesto editable; contrasta el criterio de tu recibo.')}<Check label="Incluir guardias pendientes en previsiones" checked={s.includePending} onChange={v=>change('includePending',v)}/><Notice>El patrón solo completa meses sin guardias y no cerrados. Un mes marcado completo con cero guardias conserva cero.</Notice></details>
 <details className="panel"><summary>IRPF y acumulados</summary><Check label="Estimar Renta Madrid en la vista anual" checked={!!s.fiscalPreset} onChange={v=>change('fiscalPreset',v?'madrid-single-employee':null)} hint="Declaración individual, asalariado soltero menor de 65 años, sin hijos, discapacidad ni familiares a cargo. Solo trabajo; sin movilidad ni deducciones adicionales. Activarla aquí mantiene tu modo de retención."/><Field label="Modo de IRPF"><select value={s.taxMode} onChange={e=>change('taxMode',e.target.value as SettingsType['taxMode'])}><option value="estimate">Retención AEAT estimada</option><option value="manual">Porcentaje de mi nómina</option></select></Field>{numeric('manualTaxPercent','IRPF manual (%)')}{numeric('minimumTaxPercent','Retención mínima (%)','15 % para relación laboral especial MIR; no es un mínimo del impuesto anual.')}{numeric('personalMinimum','Mínimo personal/familiar (€)','Solo para retenciones. Renta Madrid utiliza sus mínimos propios del perfil básico.')}<Check label="Movilidad geográfica fiscal aplicable" checked={s.geographicalMobility} onChange={v=>change('geographicalMobility',v)} hint="Mudarte no acredita por sí solo el requisito fiscal."/>{numeric('fiscalYear','Ejercicio de los importes fiscales manuales')}{numeric('annualGrossOverride','Bruto anual para estimar IRPF (€)','No añade cobros al resumen.',true)}{numeric('annualSSOverride','Cotizaciones anuales para IRPF (€)',undefined,true)}<Field label="Acumulados hasta"><input type="month" value={s.accumulatedThrough??''} onChange={e=>change('accumulatedThrough',e.target.value||null)}/></Field>{numeric('accumulatedGross','Bruto ya cobrado (€)')}{numeric('accumulatedWithheld','IRPF ya retenido (€)')}{numeric('accumulatedSS','Cotizaciones ya pagadas (€)','Vacío: estimación, no cotizaciones confirmadas.',true)}<Notice>Retención: trabajador activo menor de 65, situación familiar 3 sin descendientes. La Renta Madrid se estima por separado en Año y no cambia el neto de las nóminas. Ambas estimaciones cubren el perfil básico indicado.</Notice><ExternalLink href="https://sede.agenciatributaria.gob.es/Sede/Retenciones.shtml">Consultar retenciones AEAT</ExternalLink></details>
 <details className="panel"><summary>Tarifas por fecha trabajada</summary><Notice>Modificar una tabla afecta a previsiones, nunca a recibos confirmados. Los festivos especiales posteriores mantienen un supuesto editable.</Notice><Field label="Fecha del primer cambio"><input type="date" required value={s.rateChangeDate} onChange={e=>change('rateChangeDate',e.target.value)}/></Field>{(['ratesBefore','ratesAfter'] as const).map(key=><RateTable key={key} title={key==='ratesBefore'?'Antes del cambio':'Desde el cambio'} rows={s[key]} onChange={v=>change(key,v)}/>)}{s.rateVigencies.map((v,i)=><div className="rate-period" key={i}><Field label={`Vigencia posterior ${i+1}`}><input required type="date" value={v.from} onChange={e=>change('rateVigencies',s.rateVigencies.map((r,j)=>i===j?{...r,from:e.target.value}:r))}/></Field><RateTable title={`Desde ${v.from}`} rows={v.rates} onChange={rates=>change('rateVigencies',s.rateVigencies.map((r,j)=>i===j?{...r,rates}:r))}/><button type="button" onClick={()=>change('rateVigencies',s.rateVigencies.filter((_,j)=>i!==j))}>Quitar vigencia</button></div>)}<button type="button" disabled={s.rateVigencies.length>=20} onClick={()=>change('rateVigencies',[...s.rateVigencies,{from:`${2028+s.rateVigencies.length-1}-01-01`,rates:structuredClone(s.rateVigencies.at(-1)?.rates??s.ratesAfter)}])}><Plus size={18}/>Añadir vigencia para revisar</button></details>
 <details className="panel"><summary>Cotizaciones</summary>{numeric('ccMin','Base mínima CC (€)')}{numeric('atMin','Base mínima desempleo/FP (€)')}{numeric('contributionMax','Base máxima (€)')}{numeric('ccPercent','Contingencias comunes (%)')}{numeric('meiPercent','MEI empleado (%)')}{numeric('unemploymentTrainingPercent','Desempleo + formación (%)')}<p className="muted">Contrasta estos parámetros con tu contrato y recibo. La cotización de solidaridad utiliza los tramos 2026 documentados.</p></details>
 {dirty&&<p role="status" className="muted">Cambios sin guardar.</p>}<ErrorText error={error}/>{saved&&<p role="status" className="success">Ajustes guardados.</p>}<Submit busy={busy}>Guardar ajustes</Submit>
 </SafeForm>
 <Panel title="Copias e historial"><p className="muted">Veinte versiones anteriores recuperables. La copia JSON v4 incluye perfiles, calendarios y fiscalidad. Se pueden restaurar copias v1, v2 y v3 conservando sus condiciones.</p><div className="button-grid"><button onClick={onExport}><Download size={18}/>Guardar copia JSON</button><button onClick={onImport}><FileUp size={18}/>Restaurar copia</button><button onClick={onHistory}><History size={18}/>Versiones anteriores</button></div><p className="muted">La app Android anterior no abre estas nuevas copias. El enlace privado iCal no se exporta. La copia contiene importes y guardias: guárdala en un lugar privado.</p></Panel>
 <Panel title="Fuentes y vigencias"><p className="muted">Estado de los parámetros de referencia. Los ajustes manuales de tu perfil no quedan verificados por estas fuentes.</p>{ruleSets.map(r=><article className="source" key={r.id}><span className="badge">{r.status==='verified'?'Contrastado':r.status==='estimate'?'Estimación':'Pendiente de contraste'}</span><h3>{r.title}</h3><p className="muted">Desde {r.from}{r.until?` · hasta ${r.until}`:''}</p><p>{r.note}</p><ExternalLink href={r.source}>Abrir fuente oficial</ExternalLink></article>)}</Panel>
 <details className="panel"><summary>Licencias de bibliotecas y tipografía</summary><pre className="licenses">{licenses}</pre></details>
 <footer className="app-info">Mi nómina · {version}<br/>MIR SERMAS · Datos locales</footer></div>;
}

function RateTable({title,rows,onChange}:{title:string;rows:SettingsType['ratesBefore'];onChange:(r:SettingsType['ratesBefore'])=>void}){return <details className="rate-table"><summary>{title}</summary>{rows.map((r,i)=><fieldset key={i}><legend>R{i+1}</legend>{(['labour','festive','special'] as const).map(k=><NumberField key={k} label={`${typeNames[k]} · R${i+1} (€/h)`} value={r[k]} min={0} max={k==='special'?200:100} onChange={v=>onChange(rows.map((old,j)=>i===j?{...old,[k]:v??0}:old))}/>)}</fieldset>)}</details>;}
