import {useMemo,useState} from 'react';
import {type State,type Shift,blankMonth} from './domain/model';
import {addMonth,calculate,eur,monthName,rateFor,round,simulateGuardChange,standardShiftHours,suggestedType,yearCalculation} from './domain/engine';
import {Field,NumberField,Panel,Line,Notice,Check} from './ui';

export function Simulation({state,month}:{state:State;month:string}){
 const [centre,setCentre]=useState(state.settings.centres[0]?.id??''),[day,setDay]=useState(15),[lab,setLab]=useState(0),[fest,setFest]=useState(0),[target,setTarget]=useState(3000),[kind,setKind]=useState<'labour'|'festive'>('labour'),[patternLab,setPatternLab]=useState(state.settings.expectedLabour),[patternFest,setPatternFest]=useState(state.settings.expectedFestive),[vac,setVac]=useState<number|null>(null),[applyPattern,setApplyPattern]=useState(false);
 const worked=addMonth(month,-state.settings.payDelay),date=`${worked}-${String(Math.min(day,new Date(Number(worked.slice(0,4)),Number(worked.slice(5)),0).getDate())).padStart(2,'0')}`;
 function template(at:string,type:Shift['type']):Shift{return {id:'scenario',date:at,title:'Escenario',centre,hours:standardShiftHours(centre,type,state.settings),hoursMode:'standard',type,located:false,customRate:null,gradeOverride:null,status:'confirmed',sourceKey:'',sourceSignature:'',sourceCalendar:'',sourceNote:''};}
 const base=calculate(state,month),unit=template(date,'labour'),festive=template(date,suggestedType(date,centre,state.settings)==='special'?'special':'festive');
 const delta=round(lab*rateFor(unit,state.settings)+fest*rateFor(festive,state.settings));
 const scenario=base.guards.gross+delta>=0?simulateGuardChange(state,month,delta):null;
 const objective=useMemo(()=>{const s=template(date,kind==='festive'&&suggestedType(date,centre,state.settings)==='special'?'special':kind),gross=round(s.hours*rateFor(s,state.settings));for(let n=0;n<=15;n++){const r=simulateGuardChange(state,month,n*gross);if(r.after.net>=target)return {n,hours:n*s.hours,gross:n*gross,net:r.after.net};}return null;},[state,month,centre,date,kind,target]);
 const comparison=useMemo(()=>{const next=structuredClone(state),original=yearCalculation(state,Number(month.slice(0,4)));let count=0;if(!applyPattern)return {original,scenario:original,count};for(const m of original.months){if(m.month<month||m.actual||m.allocated||state.shifts.some(s=>s.date.startsWith(m.workedMonth))||state.closedShiftMonths.includes(m.workedMonth)||!m.fixed)continue;const l=template(`${m.workedMonth}-15`,'labour'),f=template(`${m.workedMonth}-15`,'festive');next.months[m.month]={...(next.months[m.month]??blankMonth()),guardGrossOverride:round(patternLab*l.hours*rateFor(l,state.settings)+patternFest*f.hours*rateFor(f,state.settings)),vacationDays:vac??state.months[m.month]?.vacationDays??0};count++;}return {original,scenario:yearCalculation(next,original.year),count};},[state,month,centre,patternLab,patternFest,vac,applyPattern]);
 return <div className="stack"><Notice>Los escenarios no modifican guardias ni recibos. La diferencia compara dos previsiones equivalentes.</Notice><Field label="Centro del escenario"><select value={centre} onChange={e=>setCentre(e.target.value)}>{state.settings.centres.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Panel title="Si cambio mis horas…"><p className="muted">Cobro en {monthName(month)}. Fecha trabajada en {monthName(worked)}.</p><NumberField label="Día trabajado para aplicar tarifa" value={day} min={1} max={31} onChange={v=>setDay(Number.isFinite(v)?Math.max(1,Math.min(31,Math.round(v??15))):15)}/><NumberField label="Variación de horas laborables" value={lab} min={-500} max={500} onChange={v=>setLab(Number.isFinite(v)?v??0:0)}/><NumberField label="Variación de horas festivas" value={fest} min={-500} max={500} onChange={v=>setFest(Number.isFinite(v)?v??0:0)}/>{scenario?<><div className="scenario-number">{scenario.delta>=0?'+':''}{eur(scenario.delta)}<small>de diferencia neta estimada</small></div><Line label="Previsión de partida" value={scenario.before.net}/><Line label="Previsión del escenario" value={scenario.after.net}/><Line label="Variación bruta" value={scenario.gross}/></>:<Notice>El escenario quitaría más bruto de guardias del previsto.</Notice>}</Panel>
 <Panel title="Objetivo neto mensual"><NumberField label="Objetivo neto (€)" min={0} max={30000} value={target} onChange={v=>setTarget(Number.isFinite(v)?v??0:0)}/><Field label="Tipo de guardia adicional"><select value={kind} onChange={e=>setKind(e.target.value as 'labour'|'festive')}><option value="labour">Laborable</option><option value="festive">Festiva</option></select></Field>{objective?<><div className="scenario-number">{objective.n}<small>guardias adicionales</small></div><Line label={`${objective.hours} horas adicionales`} value={objective.gross}/><Line label="Neto orientativo" value={objective.net}/></>:<p>El objetivo no se alcanza con las 15 guardias adicionales exploradas.</p>}<p className="muted">Simulación económica. No determina disponibilidad ni límites de jornada.</p></Panel>
 <Panel title="Patrón para los meses pendientes"><Check label="Aplicar patrón del escenario" checked={applyPattern} onChange={setApplyPattern}/><NumberField label="Laborables por mes del escenario" value={patternLab} min={0} max={15} onChange={v=>setPatternLab(Number.isFinite(v)?v??0:0)}/><NumberField label="Festivas por mes del escenario" value={patternFest} min={0} max={15} onChange={v=>setPatternFest(Number.isFinite(v)?v??0:0)}/><NumberField label="Días de vacaciones por mes del escenario" nullable hint="Vacío: conservar las vacaciones ya previstas." value={vac} min={0} max={31} onChange={v=>setVac(v===null?null:Number.isFinite(v)?v:0)}/><p className="muted">{comparison.count} meses abiertos, sin recibo ni guardias, desde el mes elegido. Tarifa del día 15 y referencias vacacionales disponibles.</p><Line label="Neto anual actual" value={comparison.original.net}/><Line label="Neto anual del escenario" value={comparison.scenario.net}/><Line label="Diferencia anual" value={round(comparison.scenario.net-comparison.original.net)} strong/><details><summary>Comparación por mes</summary>{comparison.original.months.map((m,i)=><Line key={m.month} label={monthName(m.month)} value={`${eur(m.net)} → ${eur(comparison.scenario.months[i].net)}`}/>)}</details></Panel></div>;
}
